### ISSUE TITLE
Multisite compatibility?

### ISSUE THREAD

**Issue by anthoweb-code** [cftp/external-update-api#2]
Will this plugin work in a WordPress multisite setup?

I've added the 'euapi_theme_handler' filter to the theme functions file, but I don't think this is being triggered at all. Because while in a site admin, there are no update options and while in Network Admin > Themes the functions.php of each activated theme isn't run so the notification of a new version doesn't appear here either.

Is there any other way of getting it to work do you think, perhaps by putting the filter call into a mu-plugin?

**Comment by johnbillion** [comment]
The theme update hook might need to go into a plugin or a mu-plugin, yeah. I must admit I'm not sure if the active theme's functions file gets loaded when updates are checked for.

Feel free to paste your code in here if you can't get it working.

**Comment by anthoweb-code** [comment]
That's what I suspected, here's the code - tried it in a network enabled plugin and mu-plugin but no luck. I think part of the trouble is that with multisite the themes can only be updated via the main network admin dashboard and not within each of the separates sites admin's.

<pre>function doc_update_handler( EUAPI_Handler $handler = null, EUAPI_Item $item ) {
    
    if ( 'ic-doc-default/style.css' == $item->file ) {
        $handler = new EUAPI_Handler_GitHub( array(
            'type'       => $item->type,
            'file'       => $item->file,
            'github_url' => 'https://github.com/anthoweb-code/ic-doc-default',
            'sslverify'  => false
        ) );
    }
    return $handler;
}
add_filter( 'euapi_theme_handler', 'doc_update_handler', 10, 2 );</pre>

Not sure if I have the $item->file comparison correct either - could only see an example of an implementation for a plugin in the readme?

If not in the themes functions , then where would be the usual location for adding the 'euapi_theme_handler' hook?

**Comment by anthoweb-code** [comment]
Ok, managed to get the update_handler to fire on /wp-admin/network/update-core.php (Network Admin > Updates > Available Updates), it doesn't seem to get triggered at all on the wp-admin/network/themes.php, not sure if its supposed to?

After some debugging I realised the file comparison should just be the theme folder name, so I changed that in the params and the handler now gets setup. However there seems to be an issue with the way in which the URL is constructed which then gets used by fetch_new_version() in handler-github.php.  

<pre>
EUAPI_Handler_GitHub Object
    [config] => Array
        (
            [timeout] => 5
            [type] => theme
            [access_token] => 
            [folder_name] => .
            [file_name] => ic-doc-default
            [sslverify] => 
            [base_url] => https://raw.github.com/anthoweb-code/ic-doc-default/master
            [zip_url] => https://api.github.com/repos/anthoweb-code/ic-doc-default/zipball
            [file] => ic-doc-default
            [github_url] => https://github.com/anthoweb-code/ic-doc-default
        )
</pre>

So the base_url is https://raw.github.com/anthoweb-code/ic-doc-default/master, however $this->get_file_url() returns https://raw.github.com/anthoweb-code/ic-doc-default/master/ic-doc-default

It seems to be adding the folder/file name onto the end, which results in a 404 when EUAPI::fetch is called in fetch_new_version()...

<pre>
WP_Error Object
(
    [errors] => Array
        (
            [fetch_failed] => Array
                (
                    [0] => Received HTTP response code 404 (Not Found).
                )
        )
    [error_data] => Array
        (
        )
)
</pre>

How exactly is the version comparison made, I thought it would be via style.css as this is where WP expects to find meta about each theme? 
The base_url https://raw.github.com/anthoweb-code/ic-doc-default/master seems to link to a random template file in the theme, which has no version number in it.
Sorry I'm quite new to github, perhaps there's some settings I need to adjust to make style.css the master file for the repo?

**Comment by aristath** [comment]
@anthoweb-code did you ever get this working?

**Comment by johnbillion** [comment]
This turned out to be an issue with updating themes - not tied to Multisite specifically. Fixed in the latest version.
