### ISSUE TITLE
WordPress 3.7+ compatibility

### ISSUE THREAD

**Issue by johnbillion** [cftp/external-update-api#5]
https://github.com/cftp/external-update-api/commit/8e8bbb243ffad19f889aa6356dcbf07050bc3ecc was supposed to fix compatibility with the new JSON encoding in WordPress 3.7, but it didn't. Need to fix it.

**Comment by anou** [comment]
Maybe this is why I can't manage to make it work on WP 3.8 ?
Here's my handler : 

```
      function iftheme_update_handler( EUAPI_Handler $handler = null, EUAPI_Item $item ) {
            $handler = new EUAPI_Handler_GitHub( array(
                'type'       => 'theme',
                'file'       => 'style.css',
                'github_url' => 'https://github.com/anou/iftheme',
                'sslverify'  => false
            ) );

        return $handler;

      }
      add_filter( 'euapi_theme_handler', 'iftheme_update_handler', 10, 2 );
```

I really don't know if I'm doing it right but nothing happens after many different tries

Thanks for your help.
